const URL_CLIENT = process.env.REACT_APP_URL_CLIENT;
const URL_CLIENT_ID = process.env.REACT_APP_URL_CLIENT_ID;

const URL_CONTRACTOR = process.env.REACT_APP_URL_CONTRACTOR;
const URL_PRODUCT = process.env.REACT_APP_URL_PRODUCT;
const URL_ACTIVITY = process.env.REACT_APP_URL_ACTIVITY;
const URL_CATEGORY = process.env.REACT_APP_URL_CATEGORY;

const URL_PROJECT = process.env.REACT_APP_URL_PROJECT;
const URL_PROJECT_MORE_ID = process.env.REACT_APP_URL_PROJECT_MORE_ID;

const URL_TASK = process.env.REACT_APP_URL_TASK;
const URL_TASK_MORE_ID = process.env.REACT_APP_URL_TASK_MORE_ID;

export {
  URL_CLIENT,
  URL_PROJECT,
  URL_PROJECT_MORE_ID,
  URL_TASK,
  URL_CONTRACTOR,
  URL_PRODUCT,
  URL_ACTIVITY,
  URL_CATEGORY,
  URL_TASK_MORE_ID,
  URL_CLIENT_ID,
};
